# Generated by tools/release from the artifact manifest. Do not edit by hand.
# Tap: juliankang4/homebrew-tap
class Owngit < Formula
  desc "Private Git storage and browser dashboard on your own computer"
  homepage "https://github.com/juliankang4/owngit"
  license "MIT"

  depends_on "git"

  on_macos do
    on_arm do
      url "https://github.com/juliankang4/owngit/releases/download/v1.1.3/owngit_1.1.3_darwin_arm64.tar.gz"
      sha256 "aa53e6312d7b77f177a7a920188838fa70d9a678c1f5c43f7dd7d6fdec0fd3c9"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/juliankang4/owngit/releases/download/v1.1.3/owngit_1.1.3_linux_amd64.tar.gz"
      sha256 "d696cca28c459c199f36c51f3c73ad98771318942a99a9bf9560e306447e07bb"
    end
    on_arm do
      url "https://github.com/juliankang4/owngit/releases/download/v1.1.3/owngit_1.1.3_linux_arm64.tar.gz"
      sha256 "9da6bc546f0cc0a8b4db71a48908e4b7027ad43c8cb362458760e4fc69ac7c42"
    end
  end

  def install
    bin.install "owngit"
    # OwnGit.app, the menu bar icon, next to the bin folder of the program;
    # "owngit service install" opens it from there.
    prefix.install "OwnGit.app" if OS.mac?
    prefix.install "LICENSE"
    prefix.install "THIRD_PARTY_NOTICES"
  end

  # launchd would create the service's output file readable by everyone, so
  # it is created first, for the owner only, as owngit creates its log.
  post_install_steps do
    mkdir_p "log", base: :var
    touch "log/owngit.stderr.log", base: :var
    set_permissions "log/owngit.stderr.log", "0600", base: :var
  end

  # The server log, where the first start writes the setup file path, is
  # var/log/owngit.log, which owngit keeps below 10 MiB with one older file
  # beside it. The service's own output holds only what the log cannot,
  # such as a crash report.
  service do
    run [opt_bin/"owngit", "serve", "-no-open", "--log-file", var/"log/owngit.log", "--service"]
    keep_alive true
    log_path var/"log/owngit.stderr.log"
    error_log_path var/"log/owngit.stderr.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/owngit version")
  end
end
