# Generated by tools/release from the artifact manifest. Do not edit by hand.
# Tap: juliankang4/homebrew-tap
class Owngit < Formula
  desc "Private Git storage and browser dashboard on your own computer"
  homepage "https://github.com/juliankang4/owngit"
  license "MIT"

  depends_on "git"

  on_macos do
    on_arm do
      url "https://github.com/juliankang4/owngit/releases/download/v1.0.3/owngit_1.0.3_darwin_arm64.tar.gz"
      sha256 "9543f49c789ed4123be83a069e4655707548934ed9d6eb0a9ec3382d305baf49"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/juliankang4/owngit/releases/download/v1.0.3/owngit_1.0.3_linux_amd64.tar.gz"
      sha256 "07b333cc4ba8cfaa4e0ae438887c26a413507e29eb7db0c800f861fc529ec762"
    end
    on_arm do
      url "https://github.com/juliankang4/owngit/releases/download/v1.0.3/owngit_1.0.3_linux_arm64.tar.gz"
      sha256 "211e47c3c757f7d00dde694f7531f152fb3e17d1275621eb01f99afaa5d1ac06"
    end
  end

  def install
    bin.install "owngit"
    prefix.install "LICENSE"
    prefix.install "THIRD_PARTY_NOTICES"
  end

  # The first start writes the setup file path to this log.
  service do
    run [opt_bin/"owngit", "serve", "-no-open"]
    keep_alive true
    log_path var/"log/owngit.log"
    error_log_path var/"log/owngit.log"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/owngit version")
  end
end
