# frozen_string_literal: true

# Generated by tools/release from the artifact manifest. Do not edit by hand.
# Tap: juliankang4/homebrew-tap
class Owngit < Formula
  desc "Private Git storage and browser dashboard on your own computer"
  homepage "https://github.com/juliankang4/owngit"
  license "GPL-3.0-or-later"

  depends_on "git"

  on_macos do
    on_arm do
      url "https://github.com/juliankang4/owngit/releases/download/v1.1.8/owngit_1.1.8_darwin_arm64.tar.gz"
      sha256 "f618088161043bce020e097b0428bd3b97a54a55d9beb7b5014cb5a774de33ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/juliankang4/owngit/releases/download/v1.1.8/owngit_1.1.8_linux_amd64.tar.gz"
      sha256 "650c09cfdf626515f1e6ab9c09e91d41841edb68e8137d8cec8af080a4cbe601"
    end
    on_arm do
      url "https://github.com/juliankang4/owngit/releases/download/v1.1.8/owngit_1.1.8_linux_arm64.tar.gz"
      sha256 "fdd73a2d2f4666cf337b2e2c8d811646d7854ff417b1b0984a8b734783af11fd"
    end
  end

  def install
    bin.install "owngit"
    prefix.install "OwnGit.app" if OS.mac?
    prefix.install "LICENSE"
    prefix.install "THIRD_PARTY_NOTICES"
  end

  # launchd would create the service's output file readable by everyone, so
  # it is created first, for the owner only, as owngit creates its log.
  post_install_steps do
    mkdir_p "log", base: :var
    touch "log/owngit.stderr.log", base: :var
    set_permissions "log/owngit.stderr.log", "0600", base: :var
  end

  # The server log, where the first start writes the setup file path, is
  # var/log/owngit.log, which owngit keeps below 10 MiB with one older file
  # beside it. The service's own output holds only what the log cannot,
  # such as a crash report.
  service do
    run [opt_bin/"owngit", "serve", "-no-open", "--log-file", var/"log/owngit.log", "--service"]
    keep_alive true
    stop_timeout 70
    process_type :interactive
    log_path var/"log/owngit.stderr.log"
    error_log_path var/"log/owngit.stderr.log"
  end

  def caveats
    return unless OS.mac?

    <<~EOS
      The formula runs the owngit command and server without a menu bar icon.
      To use the icon, install the matching cask app in /Applications:
        brew install --cask juliankang4/tap/owngit
      After a formula update, update the cask too:
        brew upgrade --cask juliankang4/tap/owngit
      Then run: owngit service install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/owngit version")
  end
end
